import ListJenis from './Jeni/ListJenis'
import TambahJenis from './Jeni/TambahJenis'
import Dashboard from './Dashboard'
import Icons from './Icons'
import EditJenis from './Jeni/EditJenis'
import ListKaos from './Kaos/ListKaos'
import TambahKaos from './Kaos/TambahKaos'
import EditKaos from './Kaos/EditKaos'
import Login from './Login'
import ListPesanan from './Pesanan/ListPesanan'
import Finish from './Midtans/Finish'
import Gagal from './Midtans/Gagal'
import Unfinish from './Midtans/Unfinish'
import Laporan from './Laporan/Laporan'

export {Finish, Unfinish, Gagal, Login, ListPesanan, EditKaos, TambahKaos, ListJenis, TambahJenis, Dashboard, Icons, EditJenis, ListKaos, Laporan}